version: 2
jobs:
  build:
    
    machine:
      python: 2.7.5
    
    steps:

      - run:
          name: Dependencies
          command: pip install ansible=2.7.9

      - run:
          name: Permissions for Deploy
          command: chmod +x ./bin/deploy.js

      - deploy:
          name: Execute ansible scripts
          command: ./bin/deploy.js